Added tests for HashFunctions.java
Diffblue-benchmarks/math pull request #1
Opened 2019-01-11 17:26 UTC by freddytuxworth

Hi,
I've analysed your codebase and have noticed some gaps in the coverage of HashFunctions.java.

I've written a few tests for this class with the help of Diffblue Cover.

Hopefully these tests should help you detect regressions caused by future code changes. Please let me know if you'd be interested in having more tests written for other classes within this project, I would be happy to help.

2019-01-14 14:18 UTC, JohnLBergqvist requested changes
I would remove the comments from the tests, especially the `/* testedClasses` ones. 

Also, is this the PR title we're going to use from now on? The `(from Cover with manual additions)` seems clunky to me.

Also, remove any duplicate/near-duplicate tests. I don't think we use tests for hashes because we currently just return zero all the time for them anyway, actually.

2019-01-14 14:59 UTC, petersear requested changes

2019-01-14 14:59 UTC, petersear commented on src/test/java/com/flowpowered/math/test/HashFunctionsTest.java
> +  @Rule public ExpectedException thrown = ExpectedException.none();
It doesn't look like we need this, and the associated import statement for Rule, as there are no tests which throw exceptions here.

2019-01-14 14:59 UTC, petersear commented on src/test/java/com/flowpowered/math/test/HashFunctionsTest.java
> +  }  /* testedClasses: HashFunctions */
Remove "testedClasses" comment

2019-01-14 15:10 UTC, petersear approved these changes

2019-01-14 15:18 UTC, James-Adam commented
Almost good to go. @freddytuxworth, do you know how to squash commits?

2019-01-14 15:19 UTC, petersear commented
Something I forgot to mention - it's worth including the proposed text for the PR so that can be reviewed as well. In practice, it's standard text but still worth checking.
Something else...the commits will need squashing to one and I'd suggest bringing the commit message in line with the PR title as suggested by John ie. leave out "from Cover with manual additions" (btw per James Wilson, our product should be referred to externally as "Diffblue Cover", although inevitably we will refer to it as "Cover" internally.

2019-01-16 08:18 UTC, paulkennethkent reviewed
Looks good, I would say that the only thing that is missing is very minor. In our commit messages, we usually go for a multiline message and include the following:

```
<commit message> 
These tests were written using Diffblue Cover.
Dependencies required to run the tests have also been added.  
```
Only add in the dependencies line if you've made changes to the pom.xml

2019-01-16 10:19 UTC, James-Adam commented
@freddytuxworth Once you've implemented above changes, let me know and we'll squash back down and get to submitting the PR proper.

2019-01-16 10:19 UTC, sudo-jaa approved these changes

2019-01-16 11:17 UTC, freddytuxworth commented
I've added "These tests were written using Diffblue Cover" to the commit message.

2019-01-16 12:12 UTC, JohnLBergqvist approved these changes

2019-01-16 14:04 UTC, peterschrammel commented on src/test/java/com/flowpowered/math/test/HashFunctionsTest.java
> +    final int value = 0;
Use something other than 0.

2019-02-19 12:05 UTC, closed without merging